steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/telegram-calendar-bot:$COMMIT_SHA', '.']

  # 2. Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/telegram-calendar-bot:$COMMIT_SHA']

  # 3. Deploy container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'telegram-calendar-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/telegram-calendar-bot:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Or configured auth
images:
  - 'gcr.io/$PROJECT_ID/telegram-calendar-bot:$COMMIT_SHA'
