
import asyncio
import os
import sys

# Add project root to path
sys.path.append(os.getcwd())

from app.services.groq_service import groq_service
from app.services.calendar import calendar_service
from app.core import config
import datetime

async def test_flow():
    print("🚀 Starting Logic Test...")
    
    # 1. Test Config
    print(f"Checking Config...")

    if not config.settings.TELEGRAM_BOT_TOKEN:
        print("❌ FAIL: TELEGRAM_BOT_TOKEN missing")
        return
    print("✅ Config loaded.")

    # 2. Test Groq Parsing (Basic)
    test_text = "Coffee with Nodir tomorrow at 10 AM"
    print(f"\n🧠 Testing Groq Parsing for: '{test_text}'")
    
    # 2. Parse Text
    try:
        event_data = await groq_service.parse_event(test_text)
        if event_data and 'summary' in event_data and 'start' in event_data:
            print(f"✅ Groq Response: {event_data}")
        else:
            print(f"❌ Groq failed. Response: {event_data}")
            return
    except Exception as e:
        print(f"❌ Groq Exception: {e}")
        return

    # 3. Test Calendar Insertion (Basic)
    print(f"\n📅 Testing Calendar Insertion (Basic)...")
    try:
        start_dt = datetime.datetime.fromisoformat(event_data['start'])
        end_dt = datetime.datetime.fromisoformat(event_data['end'])
        
        link = calendar_service.create_event(
            summary="[TEST] " + event_data['summary'],
            start_time=start_dt,
            end_time=end_dt,
            description="Test event generated by verification script."
        )
        print(f"✅ Basic Event created successfully!")
        print(f"🔗 Link: {link}")
    except Exception as e:
        print(f"❌ Calendar Error: {e}")
        return

    # 4. Test Advanced Features (Recurrence + Reminders)
    adv_text = "Weekly Status Meeting every Monday at 11 AM, remind 15 min"
    print(f"\n🧠 Testing Groq Parsing for Advanced: '{adv_text}'")
    
    try:
        adv_event = await groq_service.parse_event(adv_text)
        print(f"✅ Groq Advanced Response: {adv_event}")
        
        if not adv_event.get('recurrence'):
            print("❌ FAIL: Recurrence missing")
        if not adv_event.get('reminders') or adv_event['reminders'].get('useDefault'):
            print("❌ FAIL: Custom reminders missing")
            
        print(f"\n📅 Testing Calendar Insertion (Advanced)...")
        start_dt = datetime.datetime.fromisoformat(adv_event['start'])
        end_dt = datetime.datetime.fromisoformat(adv_event['end'])
        
        link = calendar_service.create_event(
            summary="[TEST-ADV] " + adv_event['summary'],
            start_time=start_dt,
            end_time=end_dt,
            description="Recurring event test.",
            recurrence=adv_event.get('recurrence'),
            reminders=adv_event.get('reminders')
        )
        print(f"✅ Advanced Event created successfully!")
        print(f"🔗 Link: {link}")

    except Exception as e:
        print(f"❌ Advanced Test Exception: {e}")
        return

    print("\n🎉 ALL SYSTEMS GO! Basic and Advanced logic works perfectly.")

if __name__ == "__main__":
    asyncio.run(test_flow())
